version: '3.1'

services:
  misp-proxy:
    build: ./saml-proxy
    container_name: misp-saml-proxy
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      idp_host: "localhost:8080"
      realm: "local-groupsec"
