version: '3.1'

services:
  misp-proxy:
    build: ./saml-proxy
    container_name: misp-saml-proxy
    restart: unless-stopped
    ports:
      - "8081:80"
      - "8082:443"
    environment:
      sp_scheme: "http"
      sp_host: "localhost"
      sp_port: "8081"
      idp_metadata_url: "http://192.168.178.205:8080/auth/realms/local-groupsec/protocol/saml/descriptor"
      proxy_destination_scheme_host: "http://192.168.178.205:8083/"
      misp_secure_header: "SAML" # must be uppercase and dont use -
      apache_self_signed_cert: "false" # generates new .crt and .key on every docker start. on false look at volume "apache-ssl"
      mellon_auth_mode: "auth" # mellon auth modes info, auth, off
    volumes:
      - apache-ssl:/usr/local/ssl/apache # provide your own crt and key named public.crt public.key in this volume and set apache_self_signed_cert = "false"

volumes:
  apache-ssl: