version: '3.1'

services:
  misp-proxy:
    build: ./saml-proxy
    container_name: misp-saml-proxy
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      sp_scheme: "http"
      sp_host: "localhost"
      sp_port: "8081"
      idp_metadata_url: "http://192.168.178.205:8080/auth/realms/local-groupsec/protocol/saml/descriptor"
      proxy_destination_scheme_host: "http://192.168.178.205:8083/"
      misp_secure_header: "SAML" # must be uppercase and dont use -
